import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^(_|ignore)' },
      ],
    },
  },
  globalIgnores([
    '.next/**',
    'next-env.d.ts',
    'media/**',
    'src/payload-types.ts',
    // Generated by Payload — do not edit.
    'src/app/(payload)/**',
  ]),
])

export default eslintConfig
