/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    organizations: Organization;
    networks: Network;
    sites: Site;
    kilns: Kiln;
    people: Person;
    vehicles: Vehicle;
    containers: Container;
    'biomass-sources': BiomassSource;
    feedstocks: Feedstock;
    batches: Batch;
    'biomass-collections': BiomassCollection;
    mixings: Mixing;
    packagings: Packaging;
    inventories: Inventory;
    applications: Application;
    stocks: Stock;
    sinks: Sink;
    documents: Document;
    templates: Template;
    files: File;
    alerts: Alert;
    'activity-logs': ActivityLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    networks: NetworksSelect<false> | NetworksSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    kilns: KilnsSelect<false> | KilnsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    containers: ContainersSelect<false> | ContainersSelect<true>;
    'biomass-sources': BiomassSourcesSelect<false> | BiomassSourcesSelect<true>;
    feedstocks: FeedstocksSelect<false> | FeedstocksSelect<true>;
    batches: BatchesSelect<false> | BatchesSelect<true>;
    'biomass-collections': BiomassCollectionsSelect<false> | BiomassCollectionsSelect<true>;
    mixings: MixingsSelect<false> | MixingsSelect<true>;
    packagings: PackagingsSelect<false> | PackagingsSelect<true>;
    inventories: InventoriesSelect<false> | InventoriesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    stocks: StocksSelect<false> | StocksSelect<true>;
    sinks: SinksSelect<false> | SinksSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    alerts: AlertsSelect<false> | AlertsSelect<true>;
    'activity-logs': ActivityLogsSelect<false> | ActivityLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    company: Company;
  };
  globalsSelect: {
    company: CompanySelect<false> | CompanySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  email: string;
  firebaseUid?: string | null;
  role: 'admin' | 'viewer';
  googleSignIn?: boolean | null;
  phone?: string | null;
  photoUrl?: string | null;
  disabled?: boolean | null;
  lastSignInAt?: string | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: string;
  code: string;
  name: string;
  country?: string | null;
  address?: string | null;
  active?: boolean | null;
  admins?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  standards?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networks".
 */
export interface Network {
  id: string;
  organization: string | Organization;
  code?: string | null;
  name: string;
  type: 'artisan' | 'csink';
  location?: string | null;
  address?: string | null;
  country?: string | null;
  lat?: number | null;
  lng?: number | null;
  active?: boolean | null;
  ceresApproved?: boolean | null;
  methaneStrategy?: string | null;
  certifiedAt?: string | null;
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  kml?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: string;
  network: string | Network;
  code?: string | null;
  name: string;
  address?: string | null;
  lat?: number | null;
  lng?: number | null;
  active?: boolean | null;
  kml?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kilns".
 */
export interface Kiln {
  id: string;
  site: string | Site;
  code?: string | null;
  name: string;
  type: 'kontiki' | 'pit';
  volumeM3?: number | null;
  shape?: string | null;
  dimensions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lat?: number | null;
  lng?: number | null;
  active?: boolean | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: string;
  name: string;
  role: 'manager' | 'supervisor' | 'operator' | 'farmer';
  email?: string | null;
  phone?: string | null;
  organization?: (string | null) | Organization;
  networks?: (string | Network)[] | null;
  sites?: (string | Site)[] | null;
  active?: boolean | null;
  otpBypass?: boolean | null;
  photo?: string | null;
  trainingDocs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  device?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  address?: string | null;
  lat?: number | null;
  lng?: number | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: string;
  network?: (string | null) | Network;
  site?: (string | null) | Site;
  name?: string | null;
  plate: string;
  type?: string | null;
  fuel?: string | null;
  emissionFactor?: number | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "containers".
 */
export interface Container {
  id: string;
  kind: 'measuring' | 'sampling';
  site?: (string | null) | Site;
  network?: (string | null) | Network;
  code?: string | null;
  name?: string | null;
  shape?: string | null;
  dimensions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  volumeL?: number | null;
  inUse?: boolean | null;
  filled?: boolean | null;
  addedAt?: string | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "biomass-sources".
 */
export interface BiomassSource {
  id: string;
  site?: (string | null) | Site;
  network?: (string | null) | Network;
  name: string;
  address?: string | null;
  lat?: number | null;
  lng?: number | null;
  active?: boolean | null;
  kml?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedstocks".
 */
export interface Feedstock {
  id: string;
  name: string;
  strategy?: ('methane' | 'compensation' | 'avoidance') | null;
  spc?: boolean | null;
  /**
   * % of dry biochar mass
   */
  carbonContent?: number | null;
  /**
   * kg/m³ of biochar
   */
  bulkDensity?: number | null;
  volumeTracking?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches".
 */
export interface Batch {
  id: string;
  code: string;
  date: string;
  network: string | Network;
  site: string | Site;
  kiln?: (string | null) | Kiln;
  startDate?: string | null;
  endedAt?: string | null;
  feedstock?: string | null;
  biomassKg?: number | null;
  biocharL?: number | null;
  bulkDensity?: number | null;
  carbonContent?: number | null;
  csinkT?: number | null;
  operator?: (string | null) | Person;
  operatorName?: string | null;
  status: 'started' | 'not_assessed' | 'approved' | 'admin_approved' | 'rejected' | 'admin_rejected';
  assessedBy?: string | null;
  assessorEmail?: string | null;
  sinkApproved?: boolean | null;
  registered?: boolean | null;
  rejectionReason?: string | null;
  assessedAt?: string | null;
  temperatureC?: number | null;
  moistureReadings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  co2EmissionKg?: number | null;
  methaneEmissionKg?: number | null;
  shortTermSinkT?: number | null;
  kilnVolumeL?: number | null;
  samplingContainer?: (string | null) | Container;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "biomass-collections".
 */
export interface BiomassCollection {
  id: string;
  date: string;
  network: string | Network;
  site: string | Site;
  farmer?: (string | null) | Person;
  feedstock?: string | null;
  source?: string | null;
  quantityKg?: number | null;
  transport?: ('manual' | 'vehicle') | null;
  vehicle?: (string | null) | Vehicle;
  vehicleDetails?: string | null;
  emissionFactor?: number | null;
  distanceKm?: number | null;
  emissions?: number | null;
  biomassSource?: (string | null) | BiomassSource;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mixings".
 */
export interface Mixing {
  id: string;
  date: string;
  batches?: (string | Batch)[] | null;
  network: string | Network;
  site: string | Site;
  mixingType?: string | null;
  biocharL?: number | null;
  otherMaterialKg?: number | null;
  totalKg?: number | null;
  bagDetails?: string | null;
  bagsCreated?: number | null;
  bagsAvailable?: number | null;
  description?: string | null;
  rejectedBiocharL?: number | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packagings".
 */
export interface Packaging {
  id: string;
  date: string;
  batches?: (string | Batch)[] | null;
  network: string | Network;
  site: string | Site;
  packagingType?: string | null;
  biocharKg?: number | null;
  mixKg?: number | null;
  bagDetails?: string | null;
  bagsCreated?: number | null;
  bagsDistributed?: number | null;
  bagsRemaining?: number | null;
  description?: string | null;
  rejectedBiocharL?: number | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventories".
 */
export interface Inventory {
  id: string;
  code?: string | null;
  network?: (string | null) | Network;
  site?: (string | null) | Site;
  batches?: (string | Batch)[] | null;
  packagingType?: string | null;
  bagType?: string | null;
  bagQuantity?: number | null;
  bagUnit?: string | null;
  actualQuantity?: number | null;
  packedAt?: string | null;
  status?: string | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: string;
  date: string;
  network?: (string | null) | Network;
  site?: (string | null) | Site;
  recipientName?: string | null;
  recipientPhone?: string | null;
  recipientAddress?: string | null;
  lat?: number | null;
  lng?: number | null;
  mixTypes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  mode?: string | null;
  vehicle?: string | null;
  kind?: string | null;
  open?: boolean | null;
  fullySinked?: boolean | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stocks".
 */
export interface Stock {
  id: string;
  stockId: string;
  code?: string | null;
  network?: (string | null) | Network;
  feedstock?: string | null;
  biocharT?: number | null;
  creditsT?: number | null;
  producedAt?: string | null;
  generatedAt?: string | null;
  partial?: boolean | null;
  deleted?: boolean | null;
  carbonContent?: number | null;
  status?: string | null;
  certificates?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sinks".
 */
export interface Sink {
  id: string;
  sinkId: string;
  date: string;
  stock?: (string | null) | Stock;
  biocharT?: number | null;
  matrixId?: string | null;
  status: 'pending' | 'approved' | 'rejected';
  deleted?: boolean | null;
  reports?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  title: string;
  category: 'csi-compliance' | 'certificate' | 'other';
  reference?: string | null;
  issuedAt?: string | null;
  expiresAt?: string | null;
  file?: (string | null) | File;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: string;
  name: string;
  mimeType: string;
  size?: number | null;
  storagePath?: string | null;
  sourcePath?: string | null;
  category?: string | null;
  ownerCollection?: string | null;
  ownerId?: string | null;
  status?: ('stored' | 'pending' | 'failed') | null;
  data?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: string;
  kind: 'kiln' | 'container';
  name: string;
  kilnType?: ('kontiki' | 'pit') | null;
  shape: string;
  unit?: ('mm' | 'cm' | 'm') | null;
  dimensions:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  volumeL?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts".
 */
export interface Alert {
  id: string;
  kind: 'bulk-density' | 'certificate' | 'kiln';
  message: string;
  network?: (string | null) | Network;
  request?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('open' | 'approved' | 'rejected' | 'dismissed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-logs".
 */
export interface ActivityLog {
  id: string;
  message: string;
  network?: (string | null) | Network;
  by?: string | null;
  actionType?: string | null;
  at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'organizations';
        value: string | Organization;
      } | null)
    | ({
        relationTo: 'networks';
        value: string | Network;
      } | null)
    | ({
        relationTo: 'sites';
        value: string | Site;
      } | null)
    | ({
        relationTo: 'kilns';
        value: string | Kiln;
      } | null)
    | ({
        relationTo: 'people';
        value: string | Person;
      } | null)
    | ({
        relationTo: 'vehicles';
        value: string | Vehicle;
      } | null)
    | ({
        relationTo: 'containers';
        value: string | Container;
      } | null)
    | ({
        relationTo: 'biomass-sources';
        value: string | BiomassSource;
      } | null)
    | ({
        relationTo: 'feedstocks';
        value: string | Feedstock;
      } | null)
    | ({
        relationTo: 'batches';
        value: string | Batch;
      } | null)
    | ({
        relationTo: 'biomass-collections';
        value: string | BiomassCollection;
      } | null)
    | ({
        relationTo: 'mixings';
        value: string | Mixing;
      } | null)
    | ({
        relationTo: 'packagings';
        value: string | Packaging;
      } | null)
    | ({
        relationTo: 'inventories';
        value: string | Inventory;
      } | null)
    | ({
        relationTo: 'applications';
        value: string | Application;
      } | null)
    | ({
        relationTo: 'stocks';
        value: string | Stock;
      } | null)
    | ({
        relationTo: 'sinks';
        value: string | Sink;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'templates';
        value: string | Template;
      } | null)
    | ({
        relationTo: 'files';
        value: string | File;
      } | null)
    | ({
        relationTo: 'alerts';
        value: string | Alert;
      } | null)
    | ({
        relationTo: 'activity-logs';
        value: string | ActivityLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  firebaseUid?: T;
  role?: T;
  googleSignIn?: T;
  phone?: T;
  photoUrl?: T;
  disabled?: T;
  lastSignInAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  id?: T;
  code?: T;
  name?: T;
  country?: T;
  address?: T;
  active?: T;
  admins?: T;
  standards?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networks_select".
 */
export interface NetworksSelect<T extends boolean = true> {
  id?: T;
  organization?: T;
  code?: T;
  name?: T;
  type?: T;
  location?: T;
  address?: T;
  country?: T;
  lat?: T;
  lng?: T;
  active?: T;
  ceresApproved?: T;
  methaneStrategy?: T;
  certifiedAt?: T;
  config?: T;
  kml?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  id?: T;
  network?: T;
  code?: T;
  name?: T;
  address?: T;
  lat?: T;
  lng?: T;
  active?: T;
  kml?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kilns_select".
 */
export interface KilnsSelect<T extends boolean = true> {
  id?: T;
  site?: T;
  code?: T;
  name?: T;
  type?: T;
  volumeM3?: T;
  shape?: T;
  dimensions?: T;
  lat?: T;
  lng?: T;
  active?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  role?: T;
  email?: T;
  phone?: T;
  organization?: T;
  networks?: T;
  sites?: T;
  active?: T;
  otpBypass?: T;
  photo?: T;
  trainingDocs?: T;
  device?: T;
  address?: T;
  lat?: T;
  lng?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  id?: T;
  network?: T;
  site?: T;
  name?: T;
  plate?: T;
  type?: T;
  fuel?: T;
  emissionFactor?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "containers_select".
 */
export interface ContainersSelect<T extends boolean = true> {
  id?: T;
  kind?: T;
  site?: T;
  network?: T;
  code?: T;
  name?: T;
  shape?: T;
  dimensions?: T;
  volumeL?: T;
  inUse?: T;
  filled?: T;
  addedAt?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "biomass-sources_select".
 */
export interface BiomassSourcesSelect<T extends boolean = true> {
  id?: T;
  site?: T;
  network?: T;
  name?: T;
  address?: T;
  lat?: T;
  lng?: T;
  active?: T;
  kml?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedstocks_select".
 */
export interface FeedstocksSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  strategy?: T;
  spc?: T;
  carbonContent?: T;
  bulkDensity?: T;
  volumeTracking?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches_select".
 */
export interface BatchesSelect<T extends boolean = true> {
  id?: T;
  code?: T;
  date?: T;
  network?: T;
  site?: T;
  kiln?: T;
  startDate?: T;
  endedAt?: T;
  feedstock?: T;
  biomassKg?: T;
  biocharL?: T;
  bulkDensity?: T;
  carbonContent?: T;
  csinkT?: T;
  operator?: T;
  operatorName?: T;
  status?: T;
  assessedBy?: T;
  assessorEmail?: T;
  sinkApproved?: T;
  registered?: T;
  rejectionReason?: T;
  assessedAt?: T;
  temperatureC?: T;
  moistureReadings?: T;
  co2EmissionKg?: T;
  methaneEmissionKg?: T;
  shortTermSinkT?: T;
  kilnVolumeL?: T;
  samplingContainer?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "biomass-collections_select".
 */
export interface BiomassCollectionsSelect<T extends boolean = true> {
  id?: T;
  date?: T;
  network?: T;
  site?: T;
  farmer?: T;
  feedstock?: T;
  source?: T;
  quantityKg?: T;
  transport?: T;
  vehicle?: T;
  vehicleDetails?: T;
  emissionFactor?: T;
  distanceKm?: T;
  emissions?: T;
  biomassSource?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mixings_select".
 */
export interface MixingsSelect<T extends boolean = true> {
  id?: T;
  date?: T;
  batches?: T;
  network?: T;
  site?: T;
  mixingType?: T;
  biocharL?: T;
  otherMaterialKg?: T;
  totalKg?: T;
  bagDetails?: T;
  bagsCreated?: T;
  bagsAvailable?: T;
  description?: T;
  rejectedBiocharL?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packagings_select".
 */
export interface PackagingsSelect<T extends boolean = true> {
  id?: T;
  date?: T;
  batches?: T;
  network?: T;
  site?: T;
  packagingType?: T;
  biocharKg?: T;
  mixKg?: T;
  bagDetails?: T;
  bagsCreated?: T;
  bagsDistributed?: T;
  bagsRemaining?: T;
  description?: T;
  rejectedBiocharL?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventories_select".
 */
export interface InventoriesSelect<T extends boolean = true> {
  id?: T;
  code?: T;
  network?: T;
  site?: T;
  batches?: T;
  packagingType?: T;
  bagType?: T;
  bagQuantity?: T;
  bagUnit?: T;
  actualQuantity?: T;
  packedAt?: T;
  status?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  id?: T;
  date?: T;
  network?: T;
  site?: T;
  recipientName?: T;
  recipientPhone?: T;
  recipientAddress?: T;
  lat?: T;
  lng?: T;
  mixTypes?: T;
  mode?: T;
  vehicle?: T;
  kind?: T;
  open?: T;
  fullySinked?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stocks_select".
 */
export interface StocksSelect<T extends boolean = true> {
  id?: T;
  stockId?: T;
  code?: T;
  network?: T;
  feedstock?: T;
  biocharT?: T;
  creditsT?: T;
  producedAt?: T;
  generatedAt?: T;
  partial?: T;
  deleted?: T;
  carbonContent?: T;
  status?: T;
  certificates?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sinks_select".
 */
export interface SinksSelect<T extends boolean = true> {
  id?: T;
  sinkId?: T;
  date?: T;
  stock?: T;
  biocharT?: T;
  matrixId?: T;
  status?: T;
  deleted?: T;
  reports?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  id?: T;
  title?: T;
  category?: T;
  reference?: T;
  issuedAt?: T;
  expiresAt?: T;
  file?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  id?: T;
  kind?: T;
  name?: T;
  kilnType?: T;
  shape?: T;
  unit?: T;
  dimensions?: T;
  volumeL?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  mimeType?: T;
  size?: T;
  storagePath?: T;
  sourcePath?: T;
  category?: T;
  ownerCollection?: T;
  ownerId?: T;
  status?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts_select".
 */
export interface AlertsSelect<T extends boolean = true> {
  id?: T;
  kind?: T;
  message?: T;
  network?: T;
  request?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-logs_select".
 */
export interface ActivityLogsSelect<T extends boolean = true> {
  id?: T;
  message?: T;
  network?: T;
  by?: T;
  actionType?: T;
  at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company".
 */
export interface Company {
  id: number;
  name: string;
  kind?: string | null;
  address?: string | null;
  email?: string | null;
  phone?: string | null;
  dmrvProvider?: string | null;
  /**
   * Contacts, documents, services, standards, app rules, projects, certificates, audit trail.
   */
  profile?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  certificateSettings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company_select".
 */
export interface CompanySelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  address?: T;
  email?: T;
  phone?: T;
  dmrvProvider?: T;
  profile?: T;
  certificateSettings?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}