/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    batches: Batch;
    media: Media;
    'credit-transactions': CreditTransaction;
    'sell-requests': SellRequest;
    users: User;
    sites: Site;
    'setup-items': SetupItem;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    batches: BatchesSelect<false> | BatchesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'credit-transactions': CreditTransactionsSelect<false> | CreditTransactionsSelect<true>;
    'sell-requests': SellRequestsSelect<false> | SellRequestsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    'setup-items': SetupItemsSelect<false> | SetupItemsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'id') | ('en' | 'id')[];
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'en' | 'id';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches".
 */
export interface Batch {
  id: number;
  /**
   * e.g. B-2309
   */
  code: string;
  status: 'progress' | 'waiting' | 'approved' | 'rejected' | 'done';
  /**
   * Current day 1–4, or 5 once every day is complete.
   */
  day: number;
  /**
   * Furthest unlocked step within the current day (0-based).
   */
  step: number;
  startedAt?: string | null;
  worker: number | User;
  site?: (number | null) | Site;
  /**
   * Biochar litres × credit factor (Settings).
   */
  credits?: number | null;
  collect?: {
    /**
     * Biomass source or farmer (v.source)
     */
    source?: string | null;
    /**
     * e.g. Corn Cob (v.btype)
     */
    biomassType?: string | null;
    /**
     * v.qty
     */
    quantity?: number | null;
    unit?: ('kg' | 'ton') | null;
    /**
     * Computed
     */
    weightKg?: number | null;
    transport?: ('manual' | 'vehicle') | null;
    /**
     * 2 required (v.bphoto)
     */
    photos?: (number | Media)[] | null;
  };
  burn?: {
    /**
     * v.kiln
     */
    kiln?: string | null;
    /**
     * 5 readings, each with a photo of the meter. Must be ≤ max moisture (v.moist)
     */
    moisture?:
      | {
          /**
           * %
           */
          value?: number | null;
          photo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * v.burn
     */
    startedAt?: string | null;
    /**
     * v.burnEnd
     */
    endedAt?: string | null;
    /**
     * 3 required (v.firePh)
     */
    firingPhotos?: (number | Media)[] | null;
    /**
     * 3 required, ~5 s each (v.fireVid)
     */
    firingVideos?: (number | Media)[] | null;
    /**
     * Usually 500–700 °C (v.temp)
     */
    temperatureC?: number | null;
    /**
     * 1 required (v.preq)
     */
    preQuenchPhotos?: (number | Media)[] | null;
    /**
     * 1 required (v.quench)
     */
    quenchPhotos?: (number | Media)[] | null;
    /**
     * v.litres
     */
    litres?: number | null;
  };
  mix?: {
    mixType?: ('compost-1-1' | 'biochar-only') | null;
    /**
     * Cannot exceed biochar made (v.mixL)
     */
    biocharUsedL?: number | null;
    /**
     * 2 required (v.mixPh)
     */
    photos?: (number | Media)[] | null;
    /**
     * v.bag
     */
    bagType?: string | null;
    /**
     * v.bags
     */
    bagCount?: number | null;
    /**
     * 1 required (v.packPh)
     */
    packPhotos?: (number | Media)[] | null;
  };
  apply?: {
    /**
     * Farmer or buyer (v.to)
     */
    receiver?: string | null;
    /**
     * v.giveBags
     */
    bagsGiven?: number | null;
    /**
     * 2 required (v.applyPh)
     */
    photos?: (number | Media)[] | null;
    latitude?: number | null;
    longitude?: number | null;
    /**
     * As shown in the app (v.loc)
     */
    locationLabel?: string | null;
  };
  review?: {
    reviewedBy?: (number | null) | User;
    reviewedAt?: string | null;
    rejectReason?: ('quench' | 'fire' | 'video' | 'moist' | 'qty') | null;
    rejectNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'supervisor' | 'worker';
  site?: (number | null) | Site;
  /**
   * As shown in the app, e.g. +62 812-0000-0000. Its digits become the login username.
   */
  phone?: string | null;
  village?: string | null;
  /**
   * Shown on the Supervisors screen, e.g. "Lead supervisor".
   */
  jobTitle?: string | null;
  avatar?: (number | null) | Media;
  lang?: ('en' | 'id') | null;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  region?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  capturedAt?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions".
 */
export interface CreditTransaction {
  id: number;
  worker: number | User;
  type: 'earned' | 'sold' | 'adjustment';
  /**
   * Credits. Positive when earned, negative when sold.
   */
  amount: number;
  date: string;
  title?: string | null;
  batch?: (number | null) | Batch;
  sellRequest?: (number | null) | SellRequest;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sell-requests".
 */
export interface SellRequest {
  id: number;
  worker: number | User;
  credits: number;
  pricePerCredit?: number | null;
  totalValue?: number | null;
  buyer?: string | null;
  status: 'pending' | 'accepted' | 'paid' | 'declined';
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "setup-items".
 */
export interface SetupItem {
  id: number;
  category:
    'kilns' | 'sources' | 'farmers' | 'vehicles' | 'bioref' | 'measure' | 'sample' | 'bags' | 'crops' | 'buyers';
  name: string;
  /**
   * Second line in the app: capacity, phone, plate number, volume…
   */
  detail?: string | null;
  site?: (number | null) | Site;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'batches';
        value: number | Batch;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'credit-transactions';
        value: number | CreditTransaction;
      } | null)
    | ({
        relationTo: 'sell-requests';
        value: number | SellRequest;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'setup-items';
        value: number | SetupItem;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches_select".
 */
export interface BatchesSelect<T extends boolean = true> {
  code?: T;
  status?: T;
  day?: T;
  step?: T;
  startedAt?: T;
  worker?: T;
  site?: T;
  credits?: T;
  collect?:
    | T
    | {
        source?: T;
        biomassType?: T;
        quantity?: T;
        unit?: T;
        weightKg?: T;
        transport?: T;
        photos?: T;
      };
  burn?:
    | T
    | {
        kiln?: T;
        moisture?:
          | T
          | {
              value?: T;
              photo?: T;
              id?: T;
            };
        startedAt?: T;
        endedAt?: T;
        firingPhotos?: T;
        firingVideos?: T;
        temperatureC?: T;
        preQuenchPhotos?: T;
        quenchPhotos?: T;
        litres?: T;
      };
  mix?:
    | T
    | {
        mixType?: T;
        biocharUsedL?: T;
        photos?: T;
        bagType?: T;
        bagCount?: T;
        packPhotos?: T;
      };
  apply?:
    | T
    | {
        receiver?: T;
        bagsGiven?: T;
        photos?: T;
        latitude?: T;
        longitude?: T;
        locationLabel?: T;
      };
  review?:
    | T
    | {
        reviewedBy?: T;
        reviewedAt?: T;
        rejectReason?: T;
        rejectNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  capturedAt?: T;
  latitude?: T;
  longitude?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions_select".
 */
export interface CreditTransactionsSelect<T extends boolean = true> {
  worker?: T;
  type?: T;
  amount?: T;
  date?: T;
  title?: T;
  batch?: T;
  sellRequest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sell-requests_select".
 */
export interface SellRequestsSelect<T extends boolean = true> {
  worker?: T;
  credits?: T;
  pricePerCredit?: T;
  totalValue?: T;
  buyer?: T;
  status?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  site?: T;
  phone?: T;
  village?: T;
  jobTitle?: T;
  avatar?: T;
  lang?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  region?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "setup-items_select".
 */
export interface SetupItemsSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  detail?: T;
  site?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Credits earned per litre of biochar (CREDIT_FACTOR).
   */
  creditFactor: number;
  /**
   * CREDIT_PRICE
   */
  creditPrice: number;
  /**
   * Credits needed before a worker can sell (CREDIT_GOAL).
   */
  creditGoal: number;
  /**
   * Readings above this block the burn (MAX_MOISTURE).
   */
  maxMoisture: number;
  defaultBuyer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  creditFactor?: T;
  creditPrice?: T;
  creditGoal?: T;
  maxMoisture?: T;
  defaultBuyer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}